
name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test: # should run every push/ pr
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - name: Installing dependencies
        run: npm run install
      - name: Building static files
        run: npm run build
  
  production: # should run every successful merge on main? & not on PR
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.event.push.base.ref == 'refs/heads/main' && github.event.push.pull_request.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "woc-au"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
